server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-routes
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id: api-docs-patient-route
              uri: http://host.docker.internal:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients, /v3/api-docs

logging:
  level:
    root: INFO
    # These are the "Magic Three" for Gateway debugging
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive:

management:
  endpoints:
    web:
      exposure:
        include: gateway